spring.application.name=SalesManagementSystem

spring.datasource.url=jdbc:postgresql://localhost:5432/salesdb
spring.datasource.username=postgres
spring.datasource.password=testing


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9yQ1JNU3lzdGVtMTIzNDU2Nzg5
jwt.expiration=86400000